// Generated by LiveScript 1.2.0
(function(){
  $(function(){
    return $.ajax({
      url: './freq.json',
      dataType: 'json'
    }).done(function(f){
      var $h, $t, d, miss, i$, i, prepare, next, show;
      $h = $('#head');
      $t = $('#tail');
      d = [];
      miss = [];
      for (i$ = 0; i$ < 26; ++i$) {
        i = i$;
        miss[i] = 0;
      }
      prepare = function(it){
        var r, s;
        r = [];
        s = it.reduce(function(p, c){
          r.push(p);
          return p + c;
        });
        return r.map(function(it){
          return it / s;
        });
      };
      f = f.map(prepare);
      next = function(it){
        var r, k, ref$, v;
        r = Math.random();
        for (k in ref$ = f[it]) {
          v = ref$[k];
          if (r < v) {
            return parseInt(k, 10);
          }
        }
        return 25;
      };
      d.push(~~(Math.random() * 26));
      for (i$ = 1; i$ <= 3; ++i$) {
        d.push(next(d[d.length - 1]));
      }
      show = function(){
        var chars;
        chars = d.slice(0, 4).map(function(it){
          return String.fromCharCode(97 + it);
        });
        $h.text(chars.shift());
        return $t.text(chars.join(''));
      };
      show();
      return $(document).keydown(function(e){
        var k, color;
        k = e.keyCode - 65;
        color = '#fff';
        if (k !== d[0]) {
          color = '#f00';
          miss[d[0]]++;
        }
        return $h.css('color', color);
      }).keyup(function(e){
        var k, c, i$, to$;
        $h.css('color', '#eee');
        k = e.keyCode - 65;
        if (k === d[0]) {
          d.shift();
          if (d.length < 4) {
            c = next(d[d.length - 1]);
            for (i$ = 0, to$ = miss[c]; i$ <= to$; ++i$) {
              d.push(c);
            }
            miss[c] = 0;
          }
          return show();
        }
      });
    });
  });
}).call(this);
