// Generated by LiveScript 1.2.0
(function(){
  $(function(){
    return $.ajax({
      url: './freq.json',
      dataType: 'json'
    }).done(function(f){
      var $d, d, prepare, next, i$, show;
      $d = $('#display');
      d = [];
      prepare = function(it){
        var r, s;
        r = [];
        s = it.reduce(function(p, c){
          r.push(p);
          return p + c;
        });
        return r.map(function(it){
          return it / s;
        });
      };
      f = f.map(prepare);
      next = function(it){
        var r, k, ref$, v;
        r = Math.random();
        for (k in ref$ = f[it]) {
          v = ref$[k];
          if (r < v) {
            return parseInt(k, 10);
          }
        }
        return 25;
      };
      d.push(~~(Math.random() * 26));
      for (i$ = 1; i$ <= 3; ++i$) {
        d.push(next(d[d.length - 1]));
      }
      show = function(){
        return $d.text(d.map(function(it){
          return String.fromCharCode(65 + it).toLowerCase();
        }).join(''));
      };
      show();
      return $(document).keyup(function(e){
        var k;
        k = e.keyCode - 65;
        if (k === d[0]) {
          d.shift();
          d.push(next(d[d.length - 1]));
          return show();
        }
      });
    });
  });
}).call(this);
